
spring:
  profiles:
    active: dev
#  datasource:
#    url: jdbc:mysql://192.168.0.229:3306/car_transport?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
#    username: root
#    password: 123
#    driver-class-name: com.mysql.jdbc.Driver
#    type: com.zaxxer.hikari.HikariDataSource
#    hikari:
#      minimum-idle: 5
#      ## 空闲连接存活最大时间，默认600000（10分钟）
#      idle-timeout: 180000
#      ## 连接池最大连接数，默认是10
#      maximum-pool-size: 100
#      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
#      auto-commit: true
#      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#      max-lifetime: 180000
#      ## 数据库连接超时时间,默认30秒，即30000
#      connection-timeout: 30000
#      connection-test-query: SELECT 1
#
#  jpa:
#    database: mysql
#    generate-ddl: false
#    hibernate:
#      ddl-auto: none
#      naming:
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQL55Dialect
#
#  liquibase:
#    change-log: classpath:liquibase/master.xml
#    enabled: true

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    publisher-confirms: true
    virtual-host: /
    publisher-returns: true
    listener:
      simple:
        concurrency: 1  #最小消费者数量
        max-concurrency: 1  #最大消费者数量
        prefetch: 1   #在单个请求中处理的消息个数
        acknowledge-mode: manual  #消费端手动应答

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 2000  # 连接超时时间（毫秒）
logging:
  config: classpath:logback-spring.xml